import express from 'express';
import bcrypt from 'bcrypt';
import db from '../config/db.js';

const router = express.Router();

// Get all employees - EXCLUDE password
router.get('/', async (req, res) => {
  const sql = `SELECT employee_id, first_name, last_name, gender, email,
               job_title, phone, ssn, hire_date, terminate_date
               FROM employee`;
  db.query(sql, (err, results) => {
    if (err) {
      return res.status(500).json({
        message: 'Error fetching employees',
        error: err.message
      });
    }
    res.json({ data: results });
  });
});

// Get maintenance employees
router.get('/maintenance', async (req, res) => {
  const sql = `SELECT employee_id, first_name, last_name, gender, email,
               job_title, phone, hire_date
               FROM employee
               WHERE deleted_at IS NULL AND terminate_date IS NULL
               AND job_title ='Mechanical Employee'`;
  db.query(sql, (err, results) => {
    if (err) {
      return res.status(500).json({
        message: 'Error fetching employees',
        error: err.message
      });
    }
    res.json({ data: results });
  });
});

// Add new employee
router.post('/add', async (req, res) => {
  const { first_name, last_name, job_title, gender, phone, ssn, hire_date } = req.body;
  const sql = `INSERT INTO employee(first_name, last_name, job_title, gender, phone, ssn, hire_date )
              VALUES (?,?,?,?,?,?,?)`;
  db.query(sql, [first_name, last_name, job_title, gender, phone, ssn, hire_date], (err, result) => {
    if (err) {
      return res.status(500).json({
        message: 'Error adding employee',
        error: err.message
      })
    }

    // Fetch the newly created employee's email and password (generated by trigger)
    const employeeId = result.insertId;
    const fetchSql = `SELECT email, password FROM employee WHERE employee_id = ?`;
    db.query(fetchSql, [employeeId], (fetchErr, fetchResult) => {
      if (fetchErr) {
        return res.status(500).json({
          message: 'Employee added but failed to retrieve credentials',
          error: fetchErr.message
        });
      }

      const employeeData = fetchResult[0];
      res.status(201).json({
        message: 'Employee added successfully',
        employeeId: employeeId,
        email: employeeData.email,
        temporaryPassword: employeeData.password
      });
    });
  })
});

// Update an employee
router.put('/:id', async (req, res) => {
  const {
    first_name, last_name, job_title, gender,
    email, phone, ssn, hire_date, terminate_date
  } = req.body;
  const id = req.params.id;

  // Convert dates to YYYY-MM-DD
  const hireDate = hire_date ? hire_date.slice(0, 10) : null;
  const terminateDate = terminate_date ? terminate_date.slice(0, 10) : null;

  const sql = `
    UPDATE employee
    SET
      first_name = ?,
      last_name = ?,
      job_title = ?,
      gender = ?,
      email = ?,
      phone = ?,
      ssn = ?,
      hire_date = ?,
      terminate_date = ?
    WHERE employee_id = ?;
  `;
  db.query(sql, [
    first_name, last_name, job_title, gender,
    email, phone, ssn, hireDate, terminateDate, id
  ], (err, result) => {
    if (err) {
      console.error("DB error:", err);
      return res.status(500).json({
        message: 'Error updating employee',
        error: err.message
      });
    }
    res.json({ message: "Employee updated successfully", data: result });
  });
});

// Delete an employee
router.delete('/:id', async (req, res) => {
  const id = req.params.id;
  const sql = `UPDATE employee
               SET deleted_at = NOW(), terminate_date = NOW()
               WHERE employee_id = ?;`;
  db.query(sql, [id], (err, result) => {
    if (err) {
      return res.status(500).json({
        message: 'Error terminating employee',
        error: err.message
      });
    }
    res.json({ message: "Employee terminated successfully", data: result });
  });
});

// Employee Login
router.post('/login', async (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.status(400).json({
      message: 'Email and password are required'
    });
  }

  try {
    const sql = `SELECT employee_id, email, password, first_name, last_name, job_title, password_changed
                 FROM employee
                 WHERE email = ? AND deleted_at IS NULL AND terminate_date IS NULL`;
    const employees = await new Promise((resolve, reject) => {
      db.query(sql, [email], (err, results) => {
        if (err) reject(err);
        else resolve(results);
      });
    });

    if (employees.length === 0) {
      return res.status(401).json({
        message: 'Invalid email or password'
      });
    }
    const employee = employees[0];

    let isPasswordValid = false;
    if (password === employee.password) {
      isPasswordValid = true;
    } else {
      try {
        isPasswordValid = await bcrypt.compare(password, employee.password);
      } catch {
        isPasswordValid = false;
      }
    }

    if (!isPasswordValid) {
      return res.status(401).json({
        message: 'Invalid email or password'
      });
    }

    const detailSql = `SELECT employee_id, email, first_name, last_name, job_title, phone, hire_date, gender, password_changed
                       FROM employee
                       WHERE employee_id = ?`;
    const employeeDetails = await new Promise((resolve, reject) => {
      db.query(detailSql, [employee.employee_id], (err, results) => {
        if (err) reject(err);
        else resolve(results[0]);
      });
    });

    res.json({
      message: 'Login successful',
      data: {
        employee_id: employeeDetails.employee_id,
        email: employeeDetails.email,
        first_name: employeeDetails.first_name,
        last_name: employeeDetails.last_name,
        job_title: employeeDetails.job_title,
        phone: employeeDetails.phone,
        hire_date: employeeDetails.hire_date,
        gender: employeeDetails.gender,
        password_changed: employeeDetails.password_changed,
        is_employee: true
      }
    });

  } catch (err) {
    console.error('Error during employee login:', err);
    return res.status(500).json({
      message: 'Error during login',
      error: err.message
    });
  }
});

// Change employee password (first-time login)
router.post('/change-password', async (req, res) => {
  const { employee_id, new_password } = req.body;

  if (!employee_id || !new_password) {
    return res.status(400).json({
      message: 'Employee ID and new password are required'
    });
  }

  // Validate password strength
  if (new_password.length < 8) {
    return res.status(400).json({
      message: 'Password must be at least 8 characters long'
    });
  }

  try {
    // Hash the new password
    const hashedPassword = await bcrypt.hash(new_password, 10);

    // Update the password and set password_changed to TRUE
    const sql = `UPDATE employee
                 SET password = ?, password_changed = TRUE
                 WHERE employee_id = ? AND deleted_at IS NULL AND terminate_date IS NULL`;

    const result = await new Promise((resolve, reject) => {
      db.query(sql, [hashedPassword, employee_id], (err, result) => {
        if (err) reject(err);
        else resolve(result);
      });
    });

    if (result.affectedRows === 0) {
      return res.status(404).json({
        message: 'Employee not found or already terminated'
      });
    }

    res.json({
      message: 'Password changed successfully'
    });

  } catch (err) {
    console.error('Error changing password:', err);
    return res.status(500).json({
      message: 'Error changing password',
      error: err.message
    });
  }
});

export default router;
